"""empty message

Revision ID: 16d8b11ce32d
Revises: d7a1e805bab2
Create Date: 2020-07-25 13:33:45.827026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d8b11ce32d'
down_revision = 'd7a1e805bab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolios')
    op.add_column('security', sa.Column('asset_class_id', sa.Integer(), nullable=False))
    op.add_column('security', sa.Column('region_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'security', 'region', ['region_id'], ['id'])
    op.create_foreign_key(None, 'security', 'assetClass', ['asset_class_id'], ['id'])
    op.drop_column('security', 'asset_class')
    op.drop_column('security', 'region')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security', sa.Column('region', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('security', sa.Column('asset_class', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'security', type_='foreignkey')
    op.drop_constraint(None, 'security', type_='foreignkey')
    op.drop_column('security', 'region_id')
    op.drop_column('security', 'asset_class_id')
    op.create_table('portfolios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('security', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='portfolios_pkey'),
    sa.UniqueConstraint('name', name='portfolios_name_key')
    )
    # ### end Alembic commands ###
