"""Initial migration.

Revision ID: d7a1e805bab2
Revises: 
Create Date: 2020-07-25 10:41:54.991533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a1e805bab2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assetClass', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'assetClass', ['name'])
    op.alter_column('portfolios', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('portfolios', 'security',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('portfolios', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'portfolios', ['name'])
    op.alter_column('region', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'region', ['name'])
    op.alter_column('security', 'asset_class',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('security', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('security', 'region',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'security', ['name'])
    op.drop_column('security', 'weight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security', sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'security', type_='unique')
    op.alter_column('security', 'region',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('security', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('security', 'asset_class',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'region', type_='unique')
    op.alter_column('region', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'portfolios', type_='unique')
    op.alter_column('portfolios', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('portfolios', 'security',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('portfolios', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'assetClass', type_='unique')
    op.alter_column('assetClass', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
